/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type OwnerEnum = "client" | "SpiderWorks" | "thirdparty";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface AppConfigs {
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  group: string;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by_id: string | null;
}

export interface Assets {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  custom_fields: Json | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  monitoring_enabled: Generated<boolean>;
  name: string;
  notes: string | null;
  primary_contact_email: string | null;
  primary_contact_name: string | null;
  status: Generated<string>;
  tags: Generated<Json>;
  tech_stack: Json | null;
  type: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by_id: string | null;
}

export interface AssetScopes {
  asset_id: string;
  scope_id: string;
}

export interface AssetServers {
  asset_id: string;
  server_id: string;
}

export interface AuditLogs {
  action: string;
  actor_id: string | null;
  after: Json | null;
  before: Json | null;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  id: Generated<string>;
  ip: string | null;
}

export interface ClientAccountManagers {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  manager_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface ClientContacts {
  client_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  designation: string | null;
  email: string | null;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  name: string;
  phone: string | null;
  send_recurring_notification: boolean | null;
  should_send_notification: Generated<boolean | null>;
  should_send_wp_notification: boolean | null;
  updated_by: string | null;
}

export interface Clients {
  address: string | null;
  company: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  custom_fields: Json | null;
  deleted_at: Timestamp | null;
  email: string | null;
  external_id: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  notes: string | null;
  phone: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface ClientTags {
  client_id: string;
  tag_id: string;
}

export interface ContractAssets {
  asset_id: string;
  contract_id: string;
}

export interface ContractRenewals {
  amount: Numeric | null;
  contract_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  new_end_date: Timestamp | null;
  new_start_date: Timestamp | null;
  notes: string | null;
  previous_end_date: Timestamp | null;
  renewed_at: Generated<Timestamp>;
}

export interface Contracts {
  amount: Numeric;
  auto_renew: Generated<boolean>;
  billing_cycle: string;
  client_id: string;
  contract_number: string | null;
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  currency: Generated<string>;
  deleted_at: Timestamp | null;
  end_date: Timestamp;
  id: Generated<string>;
  label: string | null;
  renewal_date: Timestamp;
  start_date: Timestamp;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by_id: string | null;
}

export interface ContractScopes {
  contract_id: string;
  scope_id: string;
}

export interface Domains {
  asset_id: string;
  auto_renew: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  dns_status: Generated<string>;
  expiry_date: Timestamp | null;
  fqdn: string;
  health_reason: string | null;
  health_status: Generated<string>;
  id: Generated<string>;
  last_checked_at: Timestamp | null;
  last_health_check_at: Timestamp | null;
  nameservers: Generated<Json>;
  notes: string | null;
  registered_date: Timestamp | null;
  registrar_id: string | null;
  ssl_status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by_id: string | null;
  website_status: Generated<string>;
}

export interface DomainSnapshots {
  checked_at: Generated<Timestamp>;
  domain_id: string;
  expiry_date: Timestamp | null;
  id: Generated<string>;
  nameservers: Generated<Json>;
  registrar: string | null;
}

export interface InAppNotifications {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_read: Generated<boolean>;
  link: string | null;
  message: string | null;
  severity: Generated<string>;
  title: string;
  type: string;
  user_id: string;
}

export interface Incidents {
  acknowledged_by: string | null;
  cause: string | null;
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  duration_seconds: number | null;
  id: Generated<string>;
  monitor_id: string | null;
  notes: string | null;
  resolved_at: Timestamp | null;
  severity: string;
  started_at: Generated<Timestamp>;
  target_id: string | null;
  target_type: string | null;
}

export interface MonitorChecks {
  checked_at: Generated<Timestamp>;
  error_message: string | null;
  id: Generated<string>;
  monitor_id: string;
  response_time_ms: number | null;
  status: string;
  status_code: number | null;
}

export interface Monitors {
  asset_id: string;
  check_type: string;
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  current_status: Generated<string>;
  enabled: Generated<boolean>;
  expected_keyword: string | null;
  expected_status_code: number | null;
  id: Generated<string>;
  interval_seconds: Generated<number>;
  last_checked_at: Timestamp | null;
  name: string;
  target: string;
  updated_at: Generated<Timestamp>;
  updated_by_id: string | null;
}

export interface Notes {
  content: string;
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  id: Generated<string>;
  noteable_id: string;
  noteable_type: string;
  updated_at: Generated<Timestamp>;
}

export interface NotificationHistory {
  channel: string;
  delivered_at: Timestamp | null;
  failed_at: Timestamp | null;
  failure_reason: string | null;
  id: Generated<string>;
  provider_message_id: string | null;
  recipient: string;
  reminder_id: string;
  sent_at: Generated<Timestamp>;
  status: string;
}

export interface ReminderRules {
  channels: Generated<Json>;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  event_type: string;
  id: Generated<string>;
  name: string;
  recipients: Json | null;
  trigger_days: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface Reminders {
  acknowledged_at: Timestamp | null;
  channel: string;
  created_at: Generated<Timestamp>;
  failure_reason: string | null;
  id: Generated<string>;
  message: string | null;
  rule_id: string | null;
  sent_at: Timestamp | null;
  status: Generated<string>;
  target_id: string;
  target_type: string;
  title: string;
  trigger_date: Timestamp;
}

export interface RevokedTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  jti: string;
  user_id: string;
}

export interface Scopes {
  color: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  description: string | null;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Servers {
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  currency: Generated<string>;
  id: Generated<string>;
  ip_addresses: Generated<Json>;
  label: string;
  monthly_cost: Numeric | null;
  notes: string | null;
  operating_system: string | null;
  owner: Generated<OwnerEnum>;
  panel_url: string | null;
  provider_id: string;
  region: string | null;
  remarks: string | null;
  renewal_date: Timestamp | null;
  updated_at: Generated<Timestamp>;
  updated_by_id: string | null;
}

export interface ServiceProviders {
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  id: Generated<string>;
  name: string;
  notes: string | null;
  type: string;
  updated_at: Generated<Timestamp>;
  updated_by_id: string | null;
  website: string | null;
}

export interface SslCertificates {
  asset_id: string | null;
  common_name: string | null;
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  days_until_expiry: number | null;
  domain_id: string;
  health_reason: string | null;
  health_status: Generated<string>;
  id: Generated<string>;
  issuer: string | null;
  last_checked_at: Timestamp | null;
  sans: Generated<Json>;
  type: string | null;
  updated_at: Generated<Timestamp>;
  updated_by_id: string | null;
  valid_from: Timestamp | null;
  valid_to: Timestamp | null;
}

export interface SslSnapshots {
  checked_at: Generated<Timestamp>;
  id: Generated<string>;
  issuer: string | null;
  ssl_id: string;
  valid_from: Timestamp | null;
  valid_to: Timestamp | null;
}

export interface Tags {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
}

export interface Users {
  access_token: string | null;
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  last_login_at: Timestamp | null;
  name: string;
  notification_prefs: Json | null;
  password_hash: string | null;
  phone: string | null;
  remote_user_id: Int8 | null;
  role: Generated<UserRole>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  app_configs: AppConfigs;
  asset_scopes: AssetScopes;
  asset_servers: AssetServers;
  assets: Assets;
  audit_logs: AuditLogs;
  client_account_managers: ClientAccountManagers;
  client_contacts: ClientContacts;
  client_tags: ClientTags;
  clients: Clients;
  contract_assets: ContractAssets;
  contract_renewals: ContractRenewals;
  contract_scopes: ContractScopes;
  contracts: Contracts;
  domain_snapshots: DomainSnapshots;
  domains: Domains;
  in_app_notifications: InAppNotifications;
  incidents: Incidents;
  monitor_checks: MonitorChecks;
  monitors: Monitors;
  notes: Notes;
  notification_history: NotificationHistory;
  reminder_rules: ReminderRules;
  reminders: Reminders;
  revoked_tokens: RevokedTokens;
  scopes: Scopes;
  servers: Servers;
  service_providers: ServiceProviders;
  ssl_certificates: SslCertificates;
  ssl_snapshots: SslSnapshots;
  tags: Tags;
  users: Users;
}
