"use client"

import { useState } from "react"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/r-alert-dialog"
import {
  ArrowUpDown,
  Bell,
  BellDot,
  BellOff,
  CheckCheck,
  Trash2,
} from "lucide-react"
import type { ReminderListItem, ReminderStatus, ReminderChannel } from "@/types/api"

const STATUS_CONFIG: Record<ReminderStatus, { color: "amber" | "emerald" | "blue" | "red"; icon: typeof Bell; label: string }> = {
  pending: { color: "amber", icon: Bell, label: "Pending" },
  sent: { color: "emerald", icon: BellDot, label: "Sent" },
  acknowledged: { color: "blue", icon: CheckCheck, label: "Acknowledged" },
  escalated: { color: "red", icon: BellOff, label: "Escalated" },
}

const CHANNEL_LABELS: Record<ReminderChannel, string> = {
  email: "Email",
  whatsapp: "WhatsApp",
  sms: "SMS",
  slack: "Slack",
}

export type SortField = "title" | "status" | "channel" | "trigger_date" | "created_at"

interface ReminderTableProps {
  data: ReminderListItem[]
  isLoading: boolean
  sortField: SortField
  sortOrder: "asc" | "desc"
  onSort: (field: SortField) => void
  onDelete: (id: string) => void
}

function SortHeader({
  label,
  field,
  currentField,
  order,
  onSort,
}: {
  label: string
  field: SortField
  currentField: SortField
  order: "asc" | "desc"
  onSort: (field: SortField) => void
}) {
  const isActive = currentField === field
  return (
    <TableHead
      className="cursor-pointer select-none hover:text-foreground transition-colors"
      onClick={() => onSort(field)}
    >
      <div className="flex items-center gap-1">
        {label}
        <ArrowUpDown className={`size-3 transition-opacity ${isActive ? "opacity-100" : "opacity-30"}`} />
      </div>
    </TableHead>
  )
}

export function ReminderTable({
  data,
  isLoading,
  sortField,
  sortOrder,
  onSort,
  onDelete,
}: ReminderTableProps) {
  const [deleteId, setDeleteId] = useState<string | null>(null)
  const deleteItem = data.find((r) => r.id === deleteId)

  return (
    <>
      <div className="rounded-lg border border-border/60 overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow className="bg-muted/30">
              <SortHeader label="Title" field="title" currentField={sortField} order={sortOrder} onSort={onSort} />
              <TableHead>Target Type</TableHead>
              <SortHeader label="Status" field="status" currentField={sortField} order={sortOrder} onSort={onSort} />
              <TableHead>Channel</TableHead>
              <SortHeader label="Trigger Date" field="trigger_date" currentField={sortField} order={sortOrder} onSort={onSort} />
              <TableHead>Sent At</TableHead>
              <TableHead className="w-12 text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {isLoading ? (
              Array.from({ length: 8 }).map((_, i) => (
                <TableRow key={i}>
                  {Array.from({ length: 7 }).map((_, j) => (
                    <TableCell key={j}>
                      <Skeleton className="h-4 w-full" />
                    </TableCell>
                  ))}
                </TableRow>
              ))
            ) : data.length === 0 ? (
              <TableRow>
                <TableCell colSpan={7} className="text-center py-12 text-muted-foreground">
                  <div className="flex flex-col items-center gap-2">
                    <BellOff className="size-8 text-muted-foreground/40" />
                    <span>No notifications yet</span>
                    <span className="text-xs text-muted-foreground/60">
                      Notifications are auto-generated by reminder rules. Create a rule to get started.
                    </span>
                  </div>
                </TableCell>
              </TableRow>
            ) : (
              data.map((reminder) => {
                const statusCfg = STATUS_CONFIG[reminder.status]
                const StatusIcon = statusCfg.icon
                return (
                  <TableRow
                    key={reminder.id}
                    className="group transition-colors hover:bg-muted/40"
                  >
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <div className={`size-7 rounded-md flex items-center justify-center shrink-0 ${
                          reminder.status === "sent" ? "bg-emerald-50 dark:bg-emerald-950/30 text-emerald-600 dark:text-emerald-400" :
                          reminder.status === "acknowledged" ? "bg-blue-50 dark:bg-blue-950/30 text-blue-600 dark:text-blue-400" :
                          reminder.status === "escalated" ? "bg-red-50 dark:bg-red-950/30 text-red-600 dark:text-red-400" :
                          "bg-amber-50 dark:bg-amber-950/30 text-amber-600 dark:text-amber-400"
                        }`}>
                          <StatusIcon className="size-3.5" />
                        </div>
                        <div className="min-w-0">
                          <span className="font-medium truncate max-w-[220px] block">{reminder.title}</span>
                          {reminder.message && (
                            <span className="text-[11px] text-muted-foreground truncate max-w-[220px] block">{reminder.message}</span>
                          )}
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>
                      <span className="inline-flex items-center rounded-md border border-border/60 bg-accent/50 px-2 py-0.5 text-xs font-mono font-medium text-muted-foreground capitalize">
                        {reminder.target_type}
                      </span>
                    </TableCell>
                    <TableCell>
                      <Badge variant="dot" size="sm" color={statusCfg.color}>
                        {statusCfg.label}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <span className="text-xs text-muted-foreground capitalize">
                        {CHANNEL_LABELS[reminder.channel] ?? reminder.channel}
                      </span>
                    </TableCell>
                    <TableCell>
                      <span className="text-xs text-muted-foreground">
                        {new Date(reminder.trigger_date).toLocaleString()}
                      </span>
                    </TableCell>
                    <TableCell>
                      <span className="text-xs text-muted-foreground">
                        {reminder.sent_at ? new Date(reminder.sent_at).toLocaleString() : "—"}
                      </span>
                    </TableCell>
                    <TableCell>
                      <div className="flex justify-end opacity-0 group-hover:opacity-100 transition-opacity">
                        <Button
                          variant="ghost"
                          size="icon-xs"
                          className="size-7 text-destructive hover:text-destructive"
                          onClick={() => setDeleteId(reminder.id)}
                        >
                          <Trash2 className="size-3.5" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                )
              })
            )}
          </TableBody>
        </Table>
      </div>

      <AlertDialog open={!!deleteId} onOpenChange={(open) => !open && setDeleteId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Notification</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete <strong>{deleteItem?.title}</strong>? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                if (deleteId) onDelete(deleteId)
                setDeleteId(null)
              }}
              className="bg-destructive hover:bg-destructive/80"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  )
}
